# File: netlify.toml

[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
